export const homeObjOne = {
    lightBg: false,
    buttonLabel: 'CONTACT ME',
    imgStart: "",
    lightTopLine: true,
    lightText: true,
    lightTextDesc: true,
    topLine: "Hi,",
    headLine: "I'm Aphile",
    description: "Front-end Developer",
    primary: false,
    primaryContact: true,
    img: require("../../images/homePageImage.svg").default,
    alt: "Img",
    start: "",
    exist: true,
    htmlText: "",
    cssText: "",
    javascriptText: "",
    reactText: "",
    htmlColor: false,
    cssColor: false,
    reactColor: false,
    jsColor: false,
    resumeBtn: false,
    RprimaryContact: false
}

export const homeObjTwo = {
    lightBg: true,
    buttonLabel: 'HIRE ME',
    imgStart: "start",
    lightTopLine: false,
    lightText: false,
    lightTextDesc: false,
    topLine: "",
    headLine: "About",
    description: "I am a front-end react developer with a passion of developing different, complex web applications. My top three favourite resources for learning are FreeCodeCamp, Udemy and Scrimba.",
    primary: false,
    img: require("../../images/about-undraw.svg").default,
    alt: "Img",
    start: true,
    exist: true,
    htmlText: "HTML",
    cssText: "CSS",
    javascriptText: "JAVASCRIPT",
    reactText: "REACT",
    htmlColor: true,
    cssColor: true,
    reactColor: true,
    jsColor: true,
    resumeBtn: true,
    resumeButtonLabel: "CV",
    RprimaryContact: true
}